//* COMMON ACTION NAMES
export const CLEAR_ALL_DATA = "CLEAR_ALL_DATA";
//! passing this action will clear data from each and every reducer

//* SETTINGS ACTION NAMES

//CREDENTIALS
export const SAVE_CREDENTIALS = "SAVE_CREDENTIALS";
export const UNSAVE_CREDENTIALS = "UNSAVE_CREDENTIALS";

//COURSES
export const ADD_NEW_COURSE = "ADD_NEW_COURSE";
export const DELETE_COURSE = "DELETE_COURSE";
export const EDIT_COURSE_INFO = "EDIT_COURSE_INFO";

//NOTIFICATIONS
export const ADD_NEW_NOTIFICATION = "ADD_NEW_NOTIFICAITON";
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";
