//* COMMON ACTION NAMES
export const CLEAR_ALL_DATA = "CLEAR_ALL_DATA";
//! passing this action will clear data from each and every reducer

//* MODULE ACTION NAMES
export const UPDATE_MODULES = "UPDATE_MODULES";
export const USER_TOGGLE_MODULE_COMPLETE = "USER_TOGGLE_MODULE_COMPLETE";
export const USER_TOGGLE_REMOVE_MODULE = "USER_TOGGLE_REMOVE_MODULE";

//* SETTINGS ACTION NAMES

//CREDENTIALS
export const SAVE_CREDENTIALS = "SAVE_CREDENTIALS";
export const UNSAVE_CREDENTIALS = "UNSAVE_CREDENTIALS";

//COURSES
export const ADD_NEW_COURSE = "ADD_NEW_COURSE";
export const DELETE_COURSE = "DELETE_COURSE";
export const EDIT_COURSE_INFO = "EDIT_COURSE_INFO";

//NOTIFICATIONS
export const ADD_NEW_NOTIFICATION = "ADD_NEW_NOTIFICAITON";
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";
export const DISMISS_NOTIFICATION = "DISMISS_NOTIFICATION";
export const REFRESH_UPDATE_NOTIFICATION = "REFRESH_UPDATE_NOTIFICATION";
